name: Push Docker Images

on:
  workflow_dispatch:

jobs:
  push_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: izzy2lost
          password: ${{ secrets.IZZY_DOCKER_TOKEN }}

      - name: Download ARM Image
        run: |
          wget https://github.com/izzy2lost/termux-docker/releases/download/arm/termux-docker-arm.tar
          docker load -i termux-docker-arm.tar

      - name: Push ARM Image
        run: |
          docker tag termux-docker-arm:latest izzy2lost/termux-docker:arm
          docker push izzy2lost/termux-docker:arm

      - name: Download AArch64 Image
        run: |
          wget https://github.com/izzy2lost/termux-docker/releases/download/aarch64/termux-docker-aarch64.tar
          docker load -i termux-docker-aarch64.tar

      - name: Push AArch64 Image
        run: |
          docker tag termux-docker-aarch64:latest izzy2lost/termux-docker:aarch64
          docker push izzy2lost/termux-docker:aarch64
